# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from . import GUI_MessageBoxKC as msgbox


class Ui_MainWindow(object):
    def __init__(self):
        self.MainWindow=QtWidgets.QMainWindow()
        self.finish_window=False        
        
        self.project_attributes=0
        
                
    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(781, 347)
        self.label_7 = QtWidgets.QLabel(self.MainWindow)
        self.label_7.setGeometry(QtCore.QRect(120, 190, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        
        self.Textbox_name = QtWidgets.QTextEdit(self.MainWindow)
        self.Textbox_name.setGeometry(QtCore.QRect(190, 110, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Textbox_name.setFont(font)
        
        self.Title_2 = QtWidgets.QLabel(self.MainWindow)
        self.Title_2.setGeometry(QtCore.QRect(260, 30, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Title_2.setFont(font)
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setObjectName("Title_2")
        self.label_6 = QtWidgets.QLabel(self.MainWindow)
        self.label_6.setGeometry(QtCore.QRect(120, 110, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        
        self.Textbox_description = QtWidgets.QTextEdit(self.MainWindow)
        self.Textbox_description.setGeometry(QtCore.QRect(220, 180, 511, 81)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Textbox_description.setFont(font)
        
        self.Button_Create = QtWidgets.QPushButton(self.MainWindow)
        self.Button_Create.setGeometry(QtCore.QRect(450, 290, 100, 40))
        self.Button_Create.clicked.connect(self.create_project)
        
        self.Button_Cancel = QtWidgets.QPushButton(self.MainWindow)
        self.Button_Cancel.setGeometry(QtCore.QRect(630, 290, 100, 40))
        self.Button_Cancel.clicked.connect(self.cancel_window)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "New Project"))
        self.label_7.setText(_translate("MainWindow", "Description"))
        self.Title_2.setText(_translate("MainWindow", "New project"))
        self.label_6.setText(_translate("MainWindow", "Name"))
        self.Button_Create.setText(_translate("MainWindow", "Create"))
        self.Button_Cancel.setText(_translate("MainWindow", "Cancel"))


    def create_project(self):
        print("creating the project")
        if self.Textbox_name.toPlainText()=="" or self.Textbox_description.toPlainText()=="":
            print("No text was written")
            msgbox.Message_popup("Error","No Text","No text was written")
        else:

            self.project_attributes=(self.Textbox_name.toPlainText(),self.Textbox_description.toPlainText())
            print("the text was read")
            self.cancel_window()
        
    def cancel_window(self):
        self.finish_window=True
        self.MainWindow.close()


# class Message_popup:
#     def __init__(self,m_type,m_title="",m_text=""):
#         self.msg=QMessageBox()
#         self.msg.setWindowTitle(m_title)
#         self.msg.setText(m_text)
#         if m_type=="Error":
#             self.msgError()            
#         elif m_type=="Warning":
#             self.msgWarning()
#         elif m_type=="Info":
#             self.msgInfo()         
#         elif m_type=="YesorNo":
#             self.msgYesNo()
        
#     def msgError(self):
#         self.msg.setIcon(QMessageBox.Critical)
#         return self.msg.exec_()
#     def msgWarning(self):
#         self.msg.setIcon(QMessageBox.Warning)
#         return self.msg.exec_()
#     def msgInfo(self): 
#         self.msg.setIcon(QMessageBox.Information)
#         return self.msg.exec_()       
#     def msgYesNo(self): 
#         self.msg.setIcon(QMessageBox.Question)
#         self.msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
#         #self.msg.standardButton()
#         return self.msg.exec_()    

        
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     #sys.exit(app.exec_())

# ui=Ui_MainWindow()
# ui.setupUi()

# ui.MainWindow.show()
