# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ExperimentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import GUI_MessageBoxKC as msgbox

class Ui_MainWindow(QtWidgets.QMainWindow):
    
    def __init__(self,Pr_list,exp_route):
        # self.MainWindow=QtWidgets.QMainWindow()
        super(Ui_MainWindow,self).__init__()

        self.Pr_list=Pr_list
        self.ind_pr_selected=exp_route[0] #index of the selected project
        self.ind_season_selected=exp_route[1] #index of the selected season       
        self.ind_exp_selected=exp_route[2] #index of the selected experiment
        self.exp_selected=self.Pr_list[self.ind_pr_selected].seasons[self.ind_season_selected].experiments[self.ind_exp_selected]
        
        self.finish_window=False
    
    def closeEvent(self, event):
        self.finish_window=True
        self.close()
        
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1116, 690)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 226, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 98, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 131, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 226, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 226, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 98, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 131, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 226, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 98, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 226, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 98, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 131, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 98, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 98, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 197, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        
        #Labels------------------------------------------------------------------------------------------------
        self.Title_ExperimentName = QtWidgets.QLabel(self.centralwidget)
        self.Title_ExperimentName.setGeometry(QtCore.QRect(20, 30, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Title_ExperimentName.setFont(font)
        self.Title_ExperimentName.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_ExperimentName.setObjectName("Title_ExperimentName")
        
        self.label_comments = QtWidgets.QLabel(self.centralwidget)
        self.label_comments.setGeometry(QtCore.QRect(50, 290, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_comments.setFont(font)
        self.label_comments.setObjectName("label_comments")
        
        self.label_fuel = QtWidgets.QLabel(self.centralwidget)
        self.label_fuel.setGeometry(QtCore.QRect(50, 250, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_fuel.setFont(font)
        self.label_fuel.setObjectName("label_fuel")
        
        self.label_DateStart = QtWidgets.QLabel(self.centralwidget)
        self.label_DateStart.setGeometry(QtCore.QRect(50, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DateStart.setFont(font)
        self.label_DateStart.setObjectName("label_DateStart")

        self.label_DateEnd = QtWidgets.QLabel(self.centralwidget)
        self.label_DateEnd.setGeometry(QtCore.QRect(50, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DateEnd.setFont(font)
        self.label_DateEnd.setObjectName("label_DateEnd")

        self.label_DateStart_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_DateStart_2.setGeometry(QtCore.QRect(580, 100, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DateStart_2.setFont(font)
        self.label_DateStart_2.setObjectName("label_DateStart_2")

        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(350, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(160, 100, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")

        self.label_comments_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_comments_2.setGeometry(QtCore.QRect(50, 400, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_comments_2.setFont(font)
        self.label_comments_2.setObjectName("label_comments_2")   
        

        #Buttons----------------------------------------------------------------------------------
        self.Button_AnalyseData = QtWidgets.QPushButton(self.centralwidget)
        self.Button_AnalyseData.setGeometry(QtCore.QRect(840, 380, 100, 40))
        self.Button_AnalyseData.setObjectName("Button_AnalyseData")
        
        self.Button_DeleteData = QtWidgets.QPushButton(self.centralwidget)
        self.Button_DeleteData.setGeometry(QtCore.QRect(710, 380, 100, 40))
        self.Button_DeleteData.setObjectName("Button_DeleteData")
        
        self.Button_AddData = QtWidgets.QPushButton(self.centralwidget)
        self.Button_AddData.setGeometry(QtCore.QRect(960, 380, 100, 40))
        self.Button_AddData.setObjectName("Button_AddData")
        
        self.Button_ViewData = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ViewData.setGeometry(QtCore.QRect(580, 380, 100, 40))
        self.Button_ViewData.setObjectName("Button_ViewData")
        
        self.Button_Ok = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Ok.setGeometry(QtCore.QRect(960, 550, 100, 40))
        self.Button_Ok.setObjectName("Button_Ok")
        
        self.Button_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Cancel.setGeometry(QtCore.QRect(840, 550, 100, 40))
        self.Button_Cancel.setObjectName("Button_Cancel")
        
        self.Button_AddPoint = QtWidgets.QPushButton(self.centralwidget)
        self.Button_AddPoint.setGeometry(QtCore.QRect(370, 580, 100, 40))
        self.Button_AddPoint.setObjectName("Button_AddPoint")
        
        self.Button_OpenPoint = QtWidgets.QPushButton(self.centralwidget)
        self.Button_OpenPoint.setGeometry(QtCore.QRect(250, 580, 100, 40))
        self.Button_OpenPoint.setObjectName("Button_OpenPoint")
        
        
        #TextBoxes---------------------------------------------------------------------------------
        self.text_name = QtWidgets.QTextEdit(self.centralwidget)
        self.text_name.setGeometry(QtCore.QRect(160, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_name.setFont(font)

        self.text_DateStart = QtWidgets.QTextEdit(self.centralwidget)
        self.text_DateStart.setGeometry(QtCore.QRect(160, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_DateStart.setFont(font)
        self.text_DateStart.setObjectName("text_DateStart")

        self.text_TimeStart = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TimeStart.setGeometry(QtCore.QRect(350, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_TimeStart.setFont(font)
        self.text_TimeStart.setObjectName("text_TimeStart")
        
        self.text_DateEnd = QtWidgets.QTextEdit(self.centralwidget)
        self.text_DateEnd.setGeometry(QtCore.QRect(160, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_DateEnd.setFont(font)
        self.text_DateEnd.setObjectName("text_DateEnd")
        
        self.text_TimeEnd = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TimeEnd.setGeometry(QtCore.QRect(350, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_TimeEnd.setFont(font)
        self.text_TimeEnd.setObjectName("text_TimeEnd")

        self.text_fuel = QtWidgets.QTextEdit(self.centralwidget)
        self.text_fuel.setGeometry(QtCore.QRect(160, 240, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_fuel.setFont(font)
        self.text_fuel.setObjectName("text_fuel")

        self.text_bed = QtWidgets.QTextEdit(self.centralwidget)
        self.text_bed.setGeometry(QtCore.QRect(160, 250, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_bed.setFont(font)

        self.tex_comments = QtWidgets.QTextEdit(self.centralwidget)
        self.tex_comments.setGeometry(QtCore.QRect(160, 280, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tex_comments.setFont(font)
        self.tex_comments.setObjectName("tex_comments")


        #TableWidgets--------------------------------------------------------------------------
        #table widget database (table where the loaded databases will be shown)
        self.tableWidget_db = QtWidgets.QTableWidget(self.centralwidget) 
        self.tableWidget_db.setGeometry(QtCore.QRect(580, 130, 481, 221))
        self.tableWidget_db.setColumnCount(6)
        self.tableWidget_db.setRowCount(sum([len(self.exp_selected.data_experiment[k]) for k in self.exp_selected.data_experiment.keys()]))
        
        for i in range(self.tableWidget_db.columnCount()):
            item=QtWidgets.QTableWidgetItem()
            self.tableWidget_db.setHorizontalHeaderItem(i,item)
            if self.tableWidget_db.rowCount()>0:
                for j in range(self.tableWidget_db.rowCount()):
                    item=QtWidgets.QTableWidgetItem()
                    self.tableWidget_db.setItem(j, i, item)
        

        #Table points. Table where the points registered to the selected experiment will be displayed
        self.tableWidget_points = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_points.setGeometry(QtCore.QRect(50, 430, 421, 141))
        self.tableWidget_points.setColumnCount(6)
        self.tableWidget_points.setRowCount(len(self.exp_selected.points))
        
        for i in range(self.tableWidget_points.columnCount()):
            item=QtWidgets.QTableWidgetItem()
            self.tableWidget_points.setHorizontalHeaderItem(i,item)        
            if self.tableWidget_points.rowCount()>0:
                for j in range(self.tableWidget_points.rowCount()):
                    item=QtWidgets.QTableWidgetItem()
                    self.tableWidget_points.setItem(j, i, item)        
     
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName("menu1")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.menu1.addAction(self.actionOpen)
        self.menu1.addSeparator()
        self.menubar.addAction(self.menu1.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        self.Title_ExperimentName.setText(_translate("MainWindow", "Season 1/ Experiment 1"))
        self.label_comments.setText(_translate("MainWindow", "Comments"))
        self.label_fuel.setText(_translate("MainWindow", "Fuel"))
        self.label_DateStart.setText(_translate("MainWindow", "Date start"))
        self.label_DateEnd.setText(_translate("MainWindow", "Date end"))
        self.label_time.setText(_translate("MainWindow", "Time (HH:MM)"))
        self.label_date.setText(_translate("MainWindow", "Date (YYYY-MM-DD)"))
        self.label_DateStart_2.setText(_translate("MainWindow", "Data available"))
        self.label_comments_2.setText(_translate("MainWindow", "Points available"))

        self.Button_AnalyseData.setText(_translate("MainWindow", "ANALYZE DATA"))
        self.Button_DeleteData.setText(_translate("MainWindow", "DELETE DATA"))
        self.Button_AddData.setText(_translate("MainWindow", "ADD DATA"))
        self.Button_ViewData.setText(_translate("MainWindow", "VIEW DATA"))
        self.Button_Ok.setText(_translate("MainWindow", "OK"))
        self.Button_Cancel.setText(_translate("MainWindow", "CANCEL"))
        self.Button_AddPoint.setText(_translate("MainWindow", "ADD POINT"))
        self.Button_OpenPoint.setText(_translate("MainWindow", "OPEN POINT"))
        
        col_labels_db=["Index","DB Type","Date Start","Date End","Comment","Delay"]
        col_labels_points=["Index","Name","Date Start","Date End","DB added","Comment"]
        
        for c_i,c_label in enumerate(col_labels_db):
            item = self.tableWidget_db.horizontalHeaderItem(c_i)
            item.setText(_translate("MainWindow",c_label))

        for c_i,c_label in enumerate(col_labels_points):
            item = self.tableWidget_points.horizontalHeaderItem(c_i)
            item.setText(_translate("MainWindow",c_label))
        
        # __sortingEnabled = self.tableWidget.isSortingEnabled()
        # self.tableWidget.setSortingEnabled(False)
        # self.tableWidget.setSortingEnabled(__sortingEnabled)

        
        self.menu1.setTitle(_translate("MainWindow", "1"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

        text_boxes=[(self.text_name,self.exp_selected.exp_name),
                    (self.text_DateStart,self.exp_selected.date_ini.split(" ")[0]),
                    (self.text_TimeStart,self.exp_selected.date_ini.split(" ")[1]),
                    (self.text_DateEnd,self.exp_selected.date_end.split(" ")[0]),
                    (self.text_TimeEnd,self.exp_selected.date_end.split(" ")[1]),
                    (self.text_fuel,self.exp_selected.fuel_type),
                    (self.text_bed,self.exp_selected.bed_type),
                    (self.tex_comments,self.exp_selected.exp_comments)]

        for tbox in text_boxes:
            tbox[0].setText(tbox[1])
            
        tablepoints_info=lambda j: [j,self.exp_selected.points[j].point_name,
                                    self.exp_selected.points[j].date_ini,self.exp_selected.points[j].date_end,
                                    self.exp_selected.points[j].data_added.keys(),self.exp_selected.points[j].point_comments]
        for r in range(self.tableWidget_points.rowCount()):
            for c in range(self.tableWidget_points.columnCount()):
                item=self.tableWidget_points.item(r, c)
                item.setText(str(tablepoints_info(r)[c]))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     self.show()
#     sys.exit(app.exec_())


# ui=Ui_MainWindow()
# ui.setupUi(0)
# ui.show()