# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ViewInfoProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 529)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title_ViewInfoProject = QtWidgets.QLabel(self.centralwidget)
        self.Title_ViewInfoProject.setGeometry(QtCore.QRect(40, 30, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)

        #title
        self.Title_ViewInfoProject.setFont(font)
        self.Title_ViewInfoProject.setAlignment(QtCore.Qt.AlignCenter)

        #labels---------------------------------------------------------------
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(50, 110, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        
        self.label_responsible = QtWidgets.QLabel(self.centralwidget)
        self.label_responsible.setGeometry(QtCore.QRect(50, 190, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_responsible.setFont(font)
        
        self.label_description = QtWidgets.QLabel(self.centralwidget)
        self.label_description.setGeometry(QtCore.QRect(50, 290, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_description.setFont(font)
        
        #text----------------------------------------------------------------
        self.text_name = QtWidgets.QTextEdit(self.centralwidget)
        self.text_name.setGeometry(QtCore.QRect(50, 140, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_name.setFont(font)
   
        self.text_responsible = QtWidgets.QTextEdit(self.centralwidget)
        self.text_responsible.setGeometry(QtCore.QRect(50, 230, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_responsible.setFont(font)
        
        self.text_comments = QtWidgets.QTextEdit(self.centralwidget)
        self.text_comments.setGeometry(QtCore.QRect(50, 320, 501, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_comments.setFont(font)
        
        #buttons--------------------------------------------------------
        self.Button_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Cancel.setGeometry(QtCore.QRect(330, 420, 100, 40))
        
        self.Button_OK = QtWidgets.QPushButton(self.centralwidget)
        self.Button_OK.setGeometry(QtCore.QRect(450, 420, 100, 40))
        


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        #labels----------
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title_ViewInfoProject.setText(_translate("MainWindow", "View info Project"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_responsible.setText(_translate("MainWindow", "Responsible"))
        self.label_description.setText(_translate("MainWindow", "Comments"))

        #text-----------------------
        self.text_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_responsible.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_comments.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        
        #buttons------------------
        self.Button_Cancel.setText(_translate("MainWindow", "CANCEL"))
        self.Button_OK.setText(_translate("MainWindow", "OK"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_MainWindow = Ui_MainWindow()
    Ui_MainWindow.setupUi()
    Ui_MainWindow.show()
    sys.exit(app.exec_())