# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_NewSeason.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import GUI_MessageBoxKC as msgbox


class Ui_MainWindow(QtWidgets.QMainWindow):
    
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.finish_window=False
        self.season_attributes=""
   
    def closeEvent(self, event):
        self.finish_window=True
        self.close()
        
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(527, 366)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.Title_NewSeason = QtWidgets.QLabel(self.centralwidget)
        self.Title_NewSeason.setGeometry(QtCore.QRect(110, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Title_NewSeason.setFont(font)
        self.Title_NewSeason.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_NewSeason.setObjectName("Title_NewSeason")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(40, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_description = QtWidgets.QLabel(self.centralwidget)
        self.label_description.setGeometry(QtCore.QRect(40, 160, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.text_name = QtWidgets.QTextEdit(self.centralwidget)
        self.text_name.setGeometry(QtCore.QRect(150, 80, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_name.setFont(font)
        self.text_name.setObjectName("text_name")
        self.text_Description = QtWidgets.QTextEdit(self.centralwidget)
        self.text_Description.setGeometry(QtCore.QRect(150, 160, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_Description.setFont(font)
        self.text_Description.setObjectName("text_Description")
        
        #Buttons
        self.Button_Create = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Create.setGeometry(QtCore.QRect(260, 260, 100, 40))
        self.Button_Create.setObjectName("Button_Create")
        self.Button_Create.clicked.connect(self.create_season)
        
        self.Button_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Cancel.setGeometry(QtCore.QRect(390, 260, 100, 40))
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.Button_Cancel.clicked.connect(self.cancel_button)
        
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "NEW SEASON"))
        self.Title_NewSeason.setText(_translate("MainWindow", "New Season"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_description.setText(_translate("MainWindow", "Description"))
#         self.text_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
#         self.text_Description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Button_Create.setText(_translate("MainWindow", "Create"))
        self.Button_Cancel.setText(_translate("MainWindow", "Cancel"))

    
    def create_season(self):
        if self.text_name.toPlainText()=="" or self.text_Description.toPlainText()=="":
            msgbox.Message_popup("Error","Error","No text was written in one of the boxes")
        else:
            self.season_attributes=(self.text_name.toPlainText(),self.text_Description.toPlainText())
            self.cancel_button()

    def cancel_button(self):
        self.finish_window=True
        self.close()

# if __name__ == "__main__":
#     import sys
#     #app = QtWidgets.QApplication(sys.argv)
#     ui = Ui_MainWindow()
#     ui.setupUi()
#     ui.show()
#     #sys.exit(app.exec_())
