# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_AddSCADA.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    
    def __init__(self,exp_selected):
        # self.MainWindow=QtWidgets.QMainWindow()
        super(Ui_MainWindow,self).__init__()

        self.exp_selected=exp_selected
        self.scada_info=""
        
        self.finish_window=False
    
    def closeEvent(self, event):
        self.finish_window=True
        self.close()
        
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(558, 536)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label_DateStart = QtWidgets.QLabel(self.centralwidget)
        self.label_DateStart.setGeometry(QtCore.QRect(70, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DateStart.setFont(font)
        self.label_DateStart.setObjectName("label_DateStart")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(60, 40, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)

        #labels-----------------------------------------------------------------------------------------
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(180, 120, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_date.setFont(font)
                
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(370, 120, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time.setFont(font)

        self.label_DateStart = QtWidgets.QLabel(self.centralwidget)
        self.label_DateStart.setGeometry(QtCore.QRect(70, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DateStart.setFont(font)
        
        self.label_DateEnd = QtWidgets.QLabel(self.centralwidget)
        self.label_DateEnd.setGeometry(QtCore.QRect(70, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DateEnd.setFont(font)
        
        self.label_file = QtWidgets.QLabel(self.centralwidget)
        self.label_file.setGeometry(QtCore.QRect(70, 300, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_file.setFont(font)

        self.label_comments = QtWidgets.QLabel(self.centralwidget)
        self.label_comments.setGeometry(QtCore.QRect(70, 360, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_comments.setFont(font)
        
        #text boxes-------------------------------------------------------
        
        self.text_DateStart = QtWidgets.QTextEdit(self.centralwidget)
        self.text_DateStart.setGeometry(QtCore.QRect(180, 150, 161, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_DateStart.setFont(font)
        self.text_DateEnd = QtWidgets.QTextEdit(self.centralwidget)
        self.text_DateEnd.setGeometry(QtCore.QRect(180, 200, 161, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_DateEnd.setFont(font)
        
        self.text_TimeStart = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TimeStart.setGeometry(QtCore.QRect(370, 150, 111, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_TimeStart.setFont(font)
        
        self.text_TimeEnd = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TimeEnd.setGeometry(QtCore.QRect(370, 200, 111, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_TimeEnd.setFont(font)

        self.text_Filepath = QtWidgets.QTextEdit(self.centralwidget)
        self.text_Filepath.setGeometry(QtCore.QRect(110, 290, 271, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_Filepath.setFont(font)
        
        self.text_comments = QtWidgets.QTextEdit(self.centralwidget)
        self.text_comments.setGeometry(QtCore.QRect(170, 350, 311, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_comments.setFont(font)
        
        #buttons------------------------------------------------------
        self.Button_SearchFile = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SearchFile.setGeometry(QtCore.QRect(390, 289, 100, 31))
        self.Button_SearchFile.clicked.connect(self.search_file)

        self.Button_AddData = QtWidgets.QPushButton(self.centralwidget)
        self.Button_AddData.setGeometry(QtCore.QRect(390, 420, 100, 40))
        self.Button_AddData.clicked.connect(self.add_data)
        
        self.Button_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Cancel.setGeometry(QtCore.QRect(270, 420, 100, 40))
        self.Button_Cancel.clicked.connect(self.cancel_button)
       

        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_DateStart.setText(_translate("MainWindow", "Date start"))
        self.label_DateEnd.setText(_translate("MainWindow", "Date end"))        
        self.Title.setText(_translate("MainWindow", "Add Data (SCADA)"))
        self.label_comments.setText(_translate("MainWindow", "Comments"))
        self.label_file.setText(_translate("MainWindow", "File"))
        self.Button_AddData.setText(_translate("MainWindow", "ADD DATA"))
        self.label_date.setText(_translate("MainWindow", "Date (YYYY-MM-DD)"))
        self.label_time.setText(_translate("MainWindow", "TIME (HH:MM)"))
        self.Button_Cancel.setText(_translate("MainWindow", "CANCEL"))
        self.Button_SearchFile.setText(_translate("MainWindow", "Search"))
        self.Button_AddData.setText(_translate("MainWindow", "ADD DATA"))
        self.Button_Cancel.setText(_translate("MainWindow", "CANCEL"))

    def write_default_attrib(self,ind_season):
        _translate = QtCore.QCoreApplication.translate
        #print("default_attributes =",self.default_attributes)
        if self.default_attributes=="":
            d_ini="2021-01-22 10:00:00"
            d_end="2021-01-22 12:00:00"
            comments="This is SCADA_"
            self.default_attributes=(d_ini,d_end,comments)
        # print("default_attributes ",self.default_attributes)

        self.text_DateStart.setPlaceholderText(_translate("MainWindow", self.default_attributes[1].split(" ")[0]))
        self.text_TimeStart.setPlaceholderText(_translate("MainWindow", self.default_attributes[1].split(" ")[1]))
        self.text_DateEnd.setPlaceholderText(_translate("MainWindow", self.default_attributes[2].split(" ")[0]))
        self.text_TimeEnd.setPlaceholderText(_translate("MainWindow", self.default_attributes[2].split(" ")[1]))
        self.text_comments.setPlaceholderText(_translate("MainWindow", self.default_attributes[5]))

    
    def search_file(self):

        default_path=os.getcwd()
        #print(default_path)
        file_name=QtWidgets.QFileDialog.getOpenFileName(self,"Open SCADA File",default_path)
        self.text_Filepath.setText(file_name[0])

    def add_data(self):
        
        # data_type="SCADA"
        delay="00:00:00"
        # self.exp_Selected.add_data(data_type,self.text_Filepath.text(),delay,self.text_comments.text())
        # if 
        # d_ini=self.text_DateStart.toPlainText()+" "+self.text_TimeStart.toPlainText()
        # d_end=self.text_DateEnd.toPlainText()+" "+self.text_TimeEnd.toPlainText() 
        #print(the dates of the file are not within the dates of the experiment)        
        
        self.scada_info=[self.text_Filepath.text(),self.text_comments.text(),delay]
        self.cancel_button()

    def cancel_button(self):
        self.finish_window=True
        self.close()
        
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ui = Ui_MainWindow()
#     ui.setupUi()
#     ui.show()
#     sys.exit(app.exec_())

ui = Ui_MainWindow()
ui.setupUi()
ui.show()